---
title: "Digital Earths – Global Hackathon"
---

**May 12-18 2025 -- Beijing, Boulder, Oxford, Sao Paulo, Stockholm, Tokyo**

The Digital Earths Global Hackathon will bring together scientists from around the world to jointly analyze the first ever coordinated experiments of climate models simulating a full annual cycle with horizontal grid spacings of 5 km or less).  

Participants will gather at one of a number of regional nodes for the hacking, each of which will provide access to a combined data-compute resource hosting the data and proximate computing capbility for its analysis.  Each node will host at least one full annual cycle of output data standardized on a common (HEALPix) grid.  Standardization will help participants share their analysis workflows with other teams analyzing other models at other nodes, and thereby build global communities around common interests. 

## Goals

* accelerate the improvement and analysis of km-scale climate models (including regional models)
* socialize best practices in coding and data intensive applications (infrastructure and workflows)
* establish and disseminate the advantages of adopting common standards for km-scale climate information
* build solidarity and open access to resources

In addition individual centers may provide access to additional resources to supplement the standardized model outputs.  This could include output from km-scale regional models or km-scale satellite data all of which would ideally be standardized similarly to the global models.  Likewise computing capabilities could be augmented to support the application of machine learning. 

## Organization

A scientific steering committee will be responsible for the organization and will be supported by sub-committees for technical and logistical issues.

Participating teams around the world will assign someone to the sub-committees and is welcome to nominate a member for the scientific steering committee.
