---
title: Agenda template
---


This is a draft agenda based on the experiences from the nextGEMS hackathons.


## Draft agenda
- break times (catering) are exemplary and might change during the planning process; 
- beginning and end of each day depends also on room availability

| Monday |  | room(s) |
| -------- | -------- | --- |
| 12:00 -- 15:00 | preparation     | 
| 13:00 -- 15:00 | registration | e.g. foyer |
| 15:00 -- 18:00 | welcome session | large auditorium |
| evening | potential ice breaker event | foyer/off-site |
| | | |
| **Tuesday** |  |  |
| 09:00 -- 20:00 | group work   | group rooms |
| | | |
| 11:00 -- 11:30 | coffee break | e.g. foyer |
| 13:00 -- 14:30 | lunch | foyer/off-site |
| 16:00 -- 16:30 | coffee break | e.g. foyer |
| | | |
| **Wednesday** |  |  |
| 09:00 -- 20:00 | group work   |  group rooms |
| | | |
| 11:00 -- 11:30 | coffee break | e.g. foyer |
| 13:00 -- 14:30 | lunch | foyer/off-site |
| 16:00 -- 16:30 | coffee break | e.g. foyer |
| | |
| 18:30 -- 20:00 | potential keynote talk | large auditorium |
| | | |
| **Thursday** |  |  |
| 09:00 -- 20:00 | group work   | group rooms |
| | | |
| 11:00 -- 11:30 | coffee break | e.g. foyer |
| 13:00 -- 14:30 | lunch | foyer/off-site |
| 16:00 -- 16:30 | coffee break | e.g. foyer |
| | | |
| **Friday** |  |  |
| 09:00 -- 13:00 | closing session   | large auditorium |
| | | |
| 10:30 -- 11:00 | coffee break | e.g. foyer |
| 13:00 -- 14:30 | lunch | foyer/off-site |


