---
title: Logistics for hosting a hackathon site
order: 20
---

Thoughts about hackathon organization based on 4 1/2 nextGEMS hackathons.

## Participant numbers

* nextGEMS numbers:
  + Berlin, Oct 2021: 78 (17 online)
  + Vienna, Jul 2022: 106 
  + Madrid, May 2023: 134
  + Hamburg, Mar 2024: 137
  + Wageningen, Oct 2024: 71 registrations (*as of Jul 2024*)
* for the global hackathon, we expect 50--150 participants per location


## Agenda
this is the general schedule, from the Madrid hackathon onwards, which should allow most participants to travel on Monday and Friday

* Monday afternoon to Friday morning
* Monday afternoon: welcome, theme updates, general information
* Friday afternoon: work group roundup, general discussion of future steps for the project
* Tuesday to Thursday: group work
* some general discussions or keynote talks sprinkled through the week
* This is something you should decide on, how you would like to structure the week

Here is a very general [**draft agenda**](agenda_template.qmd). Might be helpful for potential venues.


## Venue

### Type of venue

nextGEMS has experienced hackathons in different types of venues: conference hotel, coworking space, university/institute building. All worked well and all have their pros and cons.

**conference hotel**  
\+ everything (meetings, accommodation, catering) at one location  
\+ great sense of community as everyone is in one location  
\+ a lot of organization is taken care of by the venue (rooms, technical  equipment, catering)  
\- usually more pricey  
\- might be boked already  

**coworking space**  
\+ designed for these types of meetings with a lot of options for work in small groups  
\+ venue organization and possibly catering can be taken care of by the venue  
\- costs for the venue  

**university/research institutes**  
\+ usually free of charge or only a small fee  
\+ can be easier to integrate "local" participants (as there is something happening just outside their offices)  
\- considerably more work for local organizers (e.g. for catering, rooms, technical equipment)  
\- availability usually depending on lecture periods  


### Rooms

* one big(ger) lecture hall that fits all participants on Monday afternoon, Friday morning, and potential keynotes
* a couple of smaller rooms for the groups to work in
    + ideally not more than 25 people in one room
    + this depends on the envisioned structure of the meetings; people on the same or similar topics should not be separated in different rooms
    + tables and chairs should be movable (that was a little bit tricky in Madrid)
* *or* we could try out only one big room with everyone. could be noisy, could be good for collaboration
* extra room(s) for video recordings (depending on the plans)
* ideally a smaller room (up to 5 people) for side meetings, people attending a video conference, etc.
* an area for coffee breaks, lunch (depends on the catering situation)
* ideally flexible seating options outside the meeting rooms, so that people can move around a bit to work one-on-one or individually (could be just chairs on the corridor, in the cafeteria, some sofas somewhere, …)
* a place where the simulation support team and the project management team can be during the week (doesn’t need to be a dedicated room, could also be in another room)
* question: how late can the rooms be accessed in the evenings?


### Infrastructure

this can usually be booked/organized later. Also, we can check and see what different IT department could provide if something is not available at the venue from the start.

* video streaming for opening and closing sessions (?), keynotes(?)
* stable wifi connection in all rooms; the traffic isn’t too much, since the data is processed at the computing centers, but the connections should be stable
* enough power outlets in the group rooms


### Catering

this can be adjusted depending on our budget

* usually two coffee breaks per full day
* and lunch
* in Berlin and Vienna, dinners were included, only one dinner was included in Madrid, Hamburg and Wageningen
* possibly an ice breaker event on the first evening
* some snacks (fruits, etc.) and beverages to be accessible also outside of coffee breaks were very well received


## Budget

* nextGEMS has a budget of 7500 EUR per hackathon for the organization 
* 15 000 EUR for travel stipends for early career researchers (master/phd students) from outside the nextGEMS project
* 150 EUR registration fee per person in Madrid, Hamburg, Wageningen. Those were mainly spent to cover for catering (coffee breaks, lunches, one dinner)