---
title: Organization time line
---
*This is an idealized time line until when tasks need to be completed. Tasks could be completed earlier of course.*

<!-- ## Organization time line -->




**as soon as possible**

* decide on locations (for people and data)
* which projects want to be involved?
* announce dates to the community, with reference to basic website?
* come up with a cool title
* what budget do we have for location costs, etc.? are there any sponsors?

**9 months before the event (August 2024)**

* decide on rough agenda ([**draft agenda**](agenda_template.qmd)), potential keynote speakers

**8 months before the event (September 2024)**

* book meeting venues

**7 months before the event (October 2024)**

**6 months before the event (November 2024)**

* plan possible side events at each location (tours)? social events, world cafe, etc.?
* define terms of reference (TOR) for hackathon participation (is necessary for nextGEMS)

**5 months before the event (December 2024)**

* website online
* registration page(s) set up
* announce hackathon
* publish schedule
* open registration (1 Jan)

**4 months before the event (January 2025)**

* application deadline for travel support (15 Jan)
* invitation letters for visa applications to be sent out

**3 months before the event (February 2025)**

* registration closes (1 Feb)
* decision on participant numbers / can we accept all registrations?
* send out confirmation about travel support (1 Feb)
* send out registration confirmation (14 Feb)
* open payment options (14 Feb)

**2 months before the event (March 2025)**

* set up communication channels for the hackathon (Mattermost, mailing list(s))
* simulations ready

**1 month before the event (April 2025)**

* workflow for data access
* participation fee payment deadline (15 April)
* send NDAs to participants

**last weeks before the event**

* badges
* signs